-- SIO Tournament : schema PostgreSQL, adapte du modele fourni.
-- Importer UNE FOIS dans une base sio_tournament vide.
-- La base et son proprietaire sont crees separement avec createdb / CREATE ROLE.
-- Aucun DROP : les donnees existantes ne sont pas supprimees.
-- mot_de_passe stocke exclusivement un hash produit par password_hash() en PHP.
-- Les regles entre tables (jeu des equipes, eligibilite des votes, etc.)
-- doivent etre controlees dans le backend.

BEGIN;

CREATE TABLE jeu (
    id_jeu INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR(100) NOT NULL,
    genre VARCHAR(100),
    nombre_joueurs_equipe SMALLINT CHECK (nombre_joueurs_equipe >= 1) NOT NULL DEFAULT 1,
    CONSTRAINT pk_jeu PRIMARY KEY (id_jeu),
    CONSTRAINT uq_jeu_nom UNIQUE (nom)
);

CREATE TABLE utilisateur (
    id_utilisateur INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    pseudo VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    mot_de_passe VARCHAR(255) NOT NULL,
    role_plateforme VARCHAR(30) CHECK (role_plateforme IN ('JOUEUR', 'ADMINISTRATEUR')) NOT NULL DEFAULT 'JOUEUR',
    etablissement VARCHAR(150),
    option_sio VARCHAR(30) CHECK (option_sio IN ('SLAM', 'SISR', 'AUTRE')),
    avatar_url VARCHAR(500),
    date_creation TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_utilisateur PRIMARY KEY (id_utilisateur),
    CONSTRAINT uq_utilisateur_pseudo UNIQUE (pseudo),
    CONSTRAINT uq_utilisateur_email UNIQUE (email)
);

CREATE TABLE equipe (
    id_equipe INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_capitaine INTEGER CHECK (id_capitaine >= 0) NOT NULL,
    id_jeu INTEGER CHECK (id_jeu >= 0) NOT NULL,
    nom VARCHAR(100) NOT NULL,
    description TEXT,
    logo_url VARCHAR(500),
    date_creation TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    statut VARCHAR(30) CHECK (statut IN ('OUVERTE', 'FERMEE', 'ARCHIVEE')) NOT NULL DEFAULT 'OUVERTE',
    CONSTRAINT pk_equipe PRIMARY KEY (id_equipe),
    CONSTRAINT uq_equipe_nom_jeu UNIQUE (nom, id_jeu),
    CONSTRAINT fk_equipe_capitaine FOREIGN KEY (id_capitaine)
        REFERENCES utilisateur (id_utilisateur)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_equipe_jeu FOREIGN KEY (id_jeu)
        REFERENCES jeu (id_jeu)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE membre_equipe (
    id_equipe INTEGER CHECK (id_equipe >= 0) NOT NULL,
    id_utilisateur INTEGER CHECK (id_utilisateur >= 0) NOT NULL,
    role_equipe VARCHAR(30) CHECK (role_equipe IN ('CAPITAINE', 'TITULAIRE', 'REMPLACANT')) NOT NULL DEFAULT 'TITULAIRE',
    date_arrivee TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_membre_equipe PRIMARY KEY (id_equipe, id_utilisateur),
    CONSTRAINT fk_membre_equipe_equipe FOREIGN KEY (id_equipe)
        REFERENCES equipe (id_equipe)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_membre_equipe_utilisateur FOREIGN KEY (id_utilisateur)
        REFERENCES utilisateur (id_utilisateur)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE tournoi (
    id_tournoi INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_jeu INTEGER CHECK (id_jeu >= 0) NOT NULL,
    id_organisateur INTEGER CHECK (id_organisateur >= 0) NOT NULL,
    nom VARCHAR(150) NOT NULL,
    description TEXT,
    date_debut TIMESTAMP WITH TIME ZONE NOT NULL,
    date_fin TIMESTAMP WITH TIME ZONE,
    date_limite_inscription TIMESTAMP WITH TIME ZONE NOT NULL,
    nombre_equipes_max SMALLINT CHECK (nombre_equipes_max >= 2),
    format_tournoi VARCHAR(30) CHECK (format_tournoi IN ('ELIMINATION_DIRECTE', 'CHAMPIONNAT', 'GROUPES_PUIS_FINALE')) NOT NULL,
    statut VARCHAR(30) CHECK (statut IN ('BROUILLON', 'INSCRIPTIONS', 'EN_COURS', 'TERMINE', 'ANNULE')) NOT NULL DEFAULT 'BROUILLON',
    CONSTRAINT pk_tournoi PRIMARY KEY (id_tournoi),
    CONSTRAINT fk_tournoi_jeu FOREIGN KEY (id_jeu)
        REFERENCES jeu (id_jeu)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_tournoi_organisateur FOREIGN KEY (id_organisateur)
        REFERENCES utilisateur (id_utilisateur)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_tournoi_dates CHECK (date_fin IS NULL OR date_fin >= date_debut),
    CONSTRAINT ck_tournoi_limite CHECK (date_limite_inscription <= date_debut)
);

CREATE TABLE inscription_tournoi (
    id_inscription INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_tournoi INTEGER CHECK (id_tournoi >= 0) NOT NULL,
    id_equipe INTEGER CHECK (id_equipe >= 0) NOT NULL,
    date_inscription TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    statut VARCHAR(30) CHECK (statut IN ('EN_ATTENTE', 'VALIDEE', 'REFUSEE', 'ANNULEE')) NOT NULL DEFAULT 'EN_ATTENTE',
    CONSTRAINT pk_inscription_tournoi PRIMARY KEY (id_inscription),
    CONSTRAINT uq_inscription_tournoi_equipe UNIQUE (id_tournoi, id_equipe),
    CONSTRAINT fk_inscription_tournoi_tournoi FOREIGN KEY (id_tournoi)
        REFERENCES tournoi (id_tournoi)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_inscription_tournoi_equipe FOREIGN KEY (id_equipe)
        REFERENCES equipe (id_equipe)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE match_esport (
    id_match INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_tournoi INTEGER CHECK (id_tournoi >= 0) NOT NULL,
    numero_tour SMALLINT CHECK (numero_tour >= 1),
    date_prevue TIMESTAMP WITH TIME ZONE,
    date_jouee TIMESTAMP WITH TIME ZONE,
    statut VARCHAR(30) CHECK (statut IN ('PLANIFIE', 'EN_COURS', 'TERMINE', 'ANNULE')) NOT NULL DEFAULT 'PLANIFIE',
    meilleur_de SMALLINT CHECK (meilleur_de >= 0) NOT NULL DEFAULT 1,
    CONSTRAINT pk_match_esport PRIMARY KEY (id_match),
    CONSTRAINT fk_match_esport_tournoi FOREIGN KEY (id_tournoi)
        REFERENCES tournoi (id_tournoi)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_match_meilleur_de CHECK (meilleur_de >= 1 AND MOD(meilleur_de, 2) = 1)
);

CREATE TABLE participation_match (
    id_match INTEGER CHECK (id_match >= 0) NOT NULL,
    id_equipe INTEGER CHECK (id_equipe >= 0) NOT NULL,
    position_equipe SMALLINT CHECK (position_equipe >= 0) NOT NULL,
    score SMALLINT CHECK (score >= 0) NOT NULL DEFAULT 0,
    gagnante BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_participation_match PRIMARY KEY (id_match, id_equipe),
    CONSTRAINT uq_participation_position UNIQUE (id_match, position_equipe),
    CONSTRAINT fk_participation_match_match FOREIGN KEY (id_match)
        REFERENCES match_esport (id_match)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_participation_match_equipe FOREIGN KEY (id_equipe)
        REFERENCES equipe (id_equipe)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT ck_participation_position CHECK (position_equipe IN (1, 2))
);

CREATE TABLE classement (
    id_classement INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_tournoi INTEGER CHECK (id_tournoi >= 0) NOT NULL,
    id_equipe INTEGER CHECK (id_equipe >= 0) NOT NULL,
    rang SMALLINT CHECK (rang >= 1),
    points INT NOT NULL DEFAULT 0,
    matchs_joues SMALLINT CHECK (matchs_joues >= 0) NOT NULL DEFAULT 0,
    victoires SMALLINT CHECK (victoires >= 0) NOT NULL DEFAULT 0,
    defaites SMALLINT CHECK (defaites >= 0) NOT NULL DEFAULT 0,
    CONSTRAINT pk_classement PRIMARY KEY (id_classement),
    CONSTRAINT uq_classement_equipe UNIQUE (id_tournoi, id_equipe),
    CONSTRAINT uq_classement_rang UNIQUE (id_tournoi, rang),
    CONSTRAINT fk_classement_tournoi FOREIGN KEY (id_tournoi)
        REFERENCES tournoi (id_tournoi)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_classement_equipe FOREIGN KEY (id_equipe)
        REFERENCES equipe (id_equipe)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT ck_classement_resultats CHECK (victoires + defaites <= matchs_joues)
);

CREATE TABLE vote_mvp (
    id_vote INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_match INTEGER CHECK (id_match >= 0) NOT NULL,
    id_votant INTEGER CHECK (id_votant >= 0) NOT NULL,
    id_joueur_choisi INTEGER CHECK (id_joueur_choisi >= 0) NOT NULL,
    date_vote TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_vote_mvp PRIMARY KEY (id_vote),
    CONSTRAINT uq_vote_mvp UNIQUE (id_match, id_votant),
    CONSTRAINT fk_vote_mvp_match FOREIGN KEY (id_match)
        REFERENCES match_esport (id_match)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_vote_mvp_votant FOREIGN KEY (id_votant)
        REFERENCES utilisateur (id_utilisateur)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_vote_mvp_joueur FOREIGN KEY (id_joueur_choisi)
        REFERENCES utilisateur (id_utilisateur)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- Index pour les recherches et les relations frequentes.
CREATE INDEX idx_equipe_capitaine ON equipe (id_capitaine);
CREATE INDEX idx_equipe_jeu ON equipe (id_jeu);
CREATE INDEX idx_membre_utilisateur ON membre_equipe (id_utilisateur);
CREATE INDEX idx_tournoi_jeu ON tournoi (id_jeu);
CREATE INDEX idx_tournoi_organisateur ON tournoi (id_organisateur);
CREATE INDEX idx_inscription_equipe ON inscription_tournoi (id_equipe);
CREATE INDEX idx_match_tournoi ON match_esport (id_tournoi);
CREATE INDEX idx_participation_equipe ON participation_match (id_equipe);
CREATE INDEX idx_classement_equipe ON classement (id_equipe);
CREATE INDEX idx_vote_votant ON vote_mvp (id_votant);
CREATE INDEX idx_vote_joueur ON vote_mvp (id_joueur_choisi);

COMMIT;
